### ISSUE TITLE
MAStats cannot save stats because Class is null

### ISSUE THREAD

**Issue by Delanooootje** [mobarena/MobArenaStats#16]
My players are joining to arenas from world "Lobby" through NPC. They can play and everything works fine. When player die, plugin respawn him in world "Lobby" on position from where he joined the arena. (spectator is disabled for arenas and exit warp not set) When last player in arena die, it throws [error](https://pastebin.com/jkex4fuC) into console and don't save stats. 

**Config:** https://pastebin.com/bYxwF3jz
**MobArena version:** build #34 from Github Actions
**MobArenaStats version:** build #6 from Github Actions

**Server version:** Paper 1.17.1 build 257
**Plugins:** 
![obrázok_2021-10-07_201019](https://user-images.githubusercontent.com/54957486/136439788-e1ad4a72-a1b7-4156-90a7-d744d49e4c10.png)

**What I tried:**
- Set exit location on world Lobby
- Remove plugin BetterRevive (I thonk that plugin is causing issue because of plugin's death handling)
- On SQLite remove .db file so plugin can generate new, later change from SQLite to MySQL (still on MySQL)

**Comment by garbagemule** [comment]
Sorry for the late response here. The error claims that the player's class is null, which shouldn't actually be possible. Do you have any concrete reproduction steps for this issue, or does it just happen "all the time"? If you don't have any issues, please try the following with two players, A and B:

- Player A joins the arena.
- Player B joins the arena.
- Player B selects a class.
- Player A leaves the arena.
- Player B hits the iron block, and the arena begins.
- Player B plays and leaves/dies.

**Comment by Ghmmy** [comment]
The error seems to be related to the auto-start-timer. 
- The setup we used that caused this issue: https://pastebin.com/YMdeFSVD
- The actual error itself: https://pastebin.com/rdtiqgQv

Upon joining the arena (with auto-ready set to true and an auto-start-timer set to any time) and not readying up (either /ma ready or clicking the iron block), the console will be presented by the null error after the session has ended (any reason: left, died or completed).
Upon joining the same arena and readying up using the command (/ma ready) or clicking the iron block, this error will not be presented upon ending the session.

Our errors are similar, but yet different in some aspects. See if disabling the auto-ready feature and/or manually ready up to see if that solved your error as well.

**Comment by Nesseley** [comment]
I also just managed to get an error and the stats not saving. 

https://pastebin.com/AbXEmw3Q looks like the same error Ghummy had? 
Config: https://pastebin.com/tEbqh5y5
I am using the auto-start timer, but I am pretty sure that we did ready up using the iron block.
