### ISSUE TITLE
Bug ?? When use projectiles pet (like blaze) and stand in the line of fire, you will take damage

### ISSUE THREAD

**Issue by KozzaX** [mobarena/MobArenaStats#18]
Hi ! As explained in discord i've noticed that projectile pets (like a blaze for exemple), harm the players and the mobs in the arena,  is it possible to prevent the projectiles pet to harm the players ?

I'm using chest-classes but you'll noticed in the config file that there is a blaze rod summoning a blaze pet normally.

Here is my config-file : https://pastebin.com/kgLid9m3

**Comment by garbagemule** [comment]
Thanks for the bug report, but please resubmit it on the MobArena repository here: https://github.com/garbagemule/MobArena/issues :)
